from ibm_watsonx_ai.foundation_models import ModelInference
from ibm_watsonx_ai.metanames import GenTextParamsMetaNames as GenParams
from ibm_watsonx_ai.metanames import EmbedTextParamsMetaNames
from ibm_watsonx_ai import Credentials
from langchain_ibm import WatsonxLLM, WatsonxEmbeddings
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_community.document_loaders import PyPDFLoader
from langchain.chains import RetrievalQA

import gradio as gr

# You can use this section to suppress warnings generated by your code:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')

# --------------------------
# Task 0: Initialize LLM (The Generator)
# --------------------------
def get_llm():
    # FIX: Changed to a supported model to prevent the WMLClientError
    model_id = 'mistralai/mistral-medium-2505' 
    
    # The generation parameters are set in this dictionary
    parameters = {
        # FIX: Replaced 'GenTextParamsMetaNames' with the alias 'GenParams'
        GenParams.TEMPERATURE: 0.5,
        GenParams.MAX_NEW_TOKENS: 256,
        GenParams.DECODING_METHOD: "sample", 
    }
    
    project_id = "skills-network"
    
    # The WatsonxLLM is initialized with the required values
    watsonx_llm = WatsonxLLM(
        model_id=model_id,
        url="https://us-south.ml.cloud.ibm.com",
        project_id=project_id,
        params=parameters,
    )

    return watsonx_llm

# --------------------------
# Task 1: Document Loader (Ingestion)
# --------------------------
def document_loader(file):
    # 1. Create the PDF loader instance using the file's name
    loader = PyPDFLoader(file.name)
    
    # 2. Load the document using the loader's .load() method
    loaded_document = loader.load()
    
    return loaded_document

# --------------------------
# Task 2: Text Splitter (Chunking)
# --------------------------
def text_splitter(data):
    text_splitter = RecursiveCharacterTextSplitter(
        chunk_size=1000,
        chunk_overlap=200,
        length_function=len,
    )
    chunks = text_splitter.split_documents(data)
    return chunks

# --------------------------
# Task 3: Embedding Model (Vectorization)
# --------------------------
def watsonx_embedding():
    embed_params = { 
        EmbedTextParamsMetaNames.TRUNCATE_INPUT_TOKENS: 3, 
        EmbedTextParamsMetaNames.RETURN_OPTIONS: {"input_text": True}, 
    } 
    watsonx_embedding = WatsonxEmbeddings( 
        model_id="ibm/slate-30m-english-rtrvr-v2",
        url="https://us-south.ml.cloud.ibm.com", 
        project_id="skills-network", 
        params=embed_params,
    ) 
    return watsonx_embedding

# --------------------------
# Task 4: Vector DB (Storage)
# --------------------------
def vector_database(chunks):
    # This function is defined in Task 3
    embedding_model = watsonx_embedding() 
    
    # Chroma.from_documents requires the list of document 'chunks' and the 'embedding_model'
    vectordb = Chroma.from_documents(chunks, embedding_model)
    return vectordb

# --------------------------
# Task 5: Retriever (Retrieval)
# --------------------------
def retriever(file):
    splits = document_loader(file)
    chunks = text_splitter(splits)
    vectordb = vector_database(chunks)
    retriever = vectordb.as_retriever()
    return retriever

# --------------------------
# Task 6: QA Chain (Answer Generation)
# --------------------------
def retriever_qa(file, query):
    llm = get_llm()
    retriever_obj = retriever(file)
    qa = RetrievalQA.from_chain_type(llm=llm, 
                                    chain_type="stuff", 
                                    retriever=retriever_obj, 
                                    return_source_documents=False)
    response = qa.invoke(query)
    return response['result']

# Create Gradio interface
rag_application = gr.Interface(
    fn=retriever_qa,
    allow_flagging="never",
    inputs=[
        gr.File(label="Upload PDF File", file_count="single", file_types=['.pdf'], type="filepath"),  # Drag and drop file upload
        gr.Textbox(label="Input Query", lines=2, placeholder="Type your question here...")
    ],
    outputs=gr.Textbox(label="Output", lines=20),
    title="RAG Chatbot",
    description="Upload a PDF document and ask any question. The chatbot will try to answer using the provided document."
)

# Launch the app
rag_application.launch(server_name="0.0.0.0", server_port=7863)